pluginManagement {
    repositories {
        maven { url uri('local-repo') }
        maven { url 'https://repo.huaweicloud.com/repository/maven/' }
        google()
        mavenCentral()
        gradlePluginPortal()
    }
}
dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.PREFER_SETTINGS)
    repositories {
        maven { url uri('local-repo') }
        maven { url 'https://repo.huaweicloud.com/repository/maven/' }
        maven { url 'https://jitpack.io' }
        google()
        mavenCentral()
    }
}

rootProject.name = "BatteryHealthApp"
include ':app'
